/*
    vld_2 — which columns differ for int_order_items__metrics
    Generated by the dbt-data-audit skill on 2026-06-09.
    Output: one row per column with has_difference true/false (binary; magnitude not shown).
    Filter applied: none
    Next  : feed columns where has_difference = true into int_order_items__metrics_vld_3 for per-column stats.
*/

{% set old_query %} -- Legacy (A)
    select
        {{ dbt_utils.generate_surrogate_key(['order_fk', 'product_fk']) }} as order_item_sk  -- standardized: recomputed to align with model's formula
        , order_fk
        , product_fk
        , employee_fk
        , customer_fk
        , shipper_fk
        , order_date
        , ship_date
        , required_delivery_date
        , discount_pct
        , unit_price / 100 as unit_price  -- standardized: seed stores unit_price as 100x actual value (e.g. 1745 → 17.45)
        , quantity
        , gross_total
        , net_total
        , freight_allocated
        , case when had_discount = 'Y' then true else false end as had_discount  -- standardized: seed stores 'Y'/'N', model stores boolean
        , cast(replace(order_number, 'LEG-', '') as int) as order_number  -- standardized: seed stores 'LEG-10249', model stores integer 10249
        , recipient_name
        , recipient_city
        , recipient_region
        , case
            when length(recipient_country) <= 3 then recipient_country
            else initcap(lower(recipient_country))
          end as recipient_country  -- standardized: seed stores ALL CAPS, model stores Title Case; short abbreviations (USA, UK) preserved
        -- LOADED_AT omitted: not present in new model (B)
    from {{ ref('legacy_int_order_items__metrics') }}
{% endset %}

{% set new_query %} -- New (B)
    select
        order_item_sk  -- standardized: recomputed to align with model's formula
        , order_fk
        , product_fk
        , employee_fk
        , customer_fk
        , shipper_fk
        , order_date
        , ship_date
        , required_delivery_date
        , discount_pct
        , unit_price
        , quantity
        , gross_total
        , net_total
        , freight_allocated
        , had_discount
        , order_number
        , recipient_name
        , recipient_city
        , recipient_region
        , recipient_country
    from {{ ref('int_order_items__metrics') }}
{% endset %}

{{
    audit_helper.compare_which_query_columns_differ(
        a_query = old_query,
        b_query = new_query,
        primary_key_columns = ['order_item_sk'],
        columns = [
            'order_fk',
            'product_fk',
            'employee_fk',
            'customer_fk',
            'shipper_fk',
            'order_date',
            'ship_date',
            'required_delivery_date',
            'discount_pct',
            'unit_price',
            'quantity',
            'gross_total',
            'net_total',
            'freight_allocated',
            'had_discount',
            'order_number',
            'recipient_name',
            'recipient_city',
            'recipient_region',
            'recipient_country'
        ]
    )
}}
