/*
    vld_3 — per-column statistics for int_order_items__metrics
    Generated by the dbt-data-audit skill on 2026-06-09.
    Output: for each column in column_list, counts of:
              perfect match / both null / null in a only / null in b only / missing from a / missing from b / values differ
    Filter applied: none
    Scope : columns flagged by vld_2 (has_difference = true):
              ship_date, unit_price, net_total, had_discount, recipient_name, recipient_country
    Next  : use models/audit_helper/patterns.md to diagnose and apply legacy-side fixes inside old_query, then re-run.
              if values-differ remains stubborn, scope vld_4 to that single column for row-level samples
*/

{% set old_query %} -- Legacy (A)
    select
        {{ dbt_utils.generate_surrogate_key(['order_fk', 'product_fk']) }} as order_item_sk  -- standardized: recomputed to align with model's formula
        , ship_date
        , unit_price / 100 as unit_price  -- standardized: seed stores unit_price as 100x actual value (e.g. 1745 → 17.45)
        , net_total  -- NOTE: 95 rows (4.44%) differ in 3rd+ decimal only; seed rounded to 2dp, model keeps full precision — acceptable precision improvement
        , case when had_discount = 'Y' then true else false end as had_discount  -- standardized: seed stores 'Y'/'N', model stores boolean
        , recipient_name
        , case
            when length(recipient_country) <= 3 then recipient_country
            else initcap(lower(recipient_country))
          end as recipient_country  -- standardized: seed stores ALL CAPS, model stores Title Case; short abbreviations (USA, UK) preserved
    from {{ ref('legacy_int_order_items__metrics') }}
{% endset %}

{% set new_query %} -- New (B)
    select
        {{ dbt_utils.generate_surrogate_key(['order_fk', 'product_fk']) }} as order_item_sk
        , ship_date
        , unit_price
        , net_total
        , had_discount
        , recipient_name  -- NOTE: 210 rows (9.81%) differ; source shipname data drifted since seed was exported — acceptable known mismatch
        , recipient_country
    from {{ ref('int_order_items__metrics') }}
{% endset %}

{% set column_list = [
    'ship_date',
    'unit_price',
    'net_total',
    'had_discount',
    'recipient_name',
    'recipient_country'
] %}

{% for column in column_list %}

    (
        {{ audit_helper.compare_column_values(
            a_query = old_query,
            b_query = new_query,
            primary_key = "order_item_sk",
            column_to_compare = column
        ) }}
    )

    {% if not loop.last %}
        union all
    {% endif %}

{% endfor %}
