/*
    vld_4 — row-level sample classification for int_order_items__metrics
    Generated by the dbt-data-audit skill on 2026-06-09.
    Output: sample rows classified as unchanged / added / removed / modified, with (col_a, col_b) pairs side by side.
    Filter applied: none
    Scope : scoped to net_total only to isolate this column's mismatch pattern.
    Next  : back to patterns.md with what the modified samples reveal.
*/

{% set old_query %} -- Legacy (A)
    select
        {{ dbt_utils.generate_surrogate_key(['order_fk', 'product_fk']) }} as order_item_sk
        , net_total
    from {{ ref('legacy_int_order_items__metrics') }}
{% endset %}

{% set new_query %} -- New (B)
    select
        {{ dbt_utils.generate_surrogate_key(['order_fk', 'product_fk']) }} as order_item_sk
        , net_total
    from {{ ref('int_order_items__metrics') }}
{% endset %}

{{
    audit_helper.compare_and_classify_query_results(
        old_query,
        new_query,
        primary_key_columns = ['order_item_sk'],
        columns = [
            'net_total'
        ]
    )
}}
